<a href="https://colab.research.google.com/github/spegas/Dacon/blob/main/Get_Stock_Data_Naver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install finance-datareader

Collecting finance-datareader
  Downloading finance_datareader-0.9.31-py3-none-any.whl (17 kB)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.2.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.62.3)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (1.1.5)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->finance-datareader) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.31 requests-file-1.5.1

In [2]:
!pip install wget

Collecting wget
  Downloading wget-3.2.zip (10 kB)
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9672 sha256=391972f710bff31c8f7fe0d59cde9232445a27a6e792db263f7fa7c71db53c15
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [3]:
import pandas as pd
import numpy as np
import os
import FinanceDataReader as fdr
import wget

from zipfile import ZipFile
from os.path import basename

In [4]:
if not os.path.isdir("base"):
  print("base 디렉토리 생성")
  os.makedirs("base")

if not os.path.isdir("price"):
  print("price 디렉토리 생성")
  os.makedirs("price")

base 디렉토리 생성
price 디렉토리 생성

In [5]:
stock_list_file_url = "https://raw.githubusercontent.com/spegas/Dacon/main/stock_list.csv"
if os.path.exists('base/stock_list.csv'):
  os.remove('base/stock_list.csv')
  print('이전에 저장된 주식 종목 리스트 파일을 삭제 합니다.')
wget.download(stock_list_file_url, 'base/stock_list.csv')
print('주식 종목 리스트 파일 다운로드 완료')

주식 종목 리스트 파일 다운로드 완료

In [6]:
stock_list_name = 'base/stock_list.csv'
pd_stock_list = pd.read_csv(stock_list_name)
pd_stock_list['종목코드'] = pd_stock_list['종목코드'].apply(lambda x : str(x).zfill(6))
pd_stock_list.head(10)

        종목명    종목코드   상장시장
0      삼성전자  005930  KOSPI
1    SK하이닉스  000660  KOSPI
2     NAVER  035420  KOSPI
3       카카오  035720  KOSPI
4  삼성바이오로직스  207940  KOSPI
5     삼성전자우  005935  KOSPI
6      LG화학  051910  KOSPI
7     삼성SDI  006400  KOSPI
8       현대차  005380  KOSPI
9      셀트리온  068270  KOSPI

In [7]:
start_date = '20200101'
end_date = '20211125'

In [8]:
for f_index in range(0, pd_stock_list.shape[0]):
  f_code = pd_stock_list.iloc[f_index]['종목코드']
  f_name = pd_stock_list.iloc[f_index]['종목명']
  price_filename = str('price/') + str(f_code) + str('_price.csv')
  if not os.path.exists(price_filename):
    f_price = fdr.DataReader(f_code, start = start_date, end = end_date)
    f_price.to_csv(price_filename)
    print('[종목코드 : %s, 종목명 : %s] 가격 정보 저장 완료' % (str(f_code), str(f_name)))
  else:
    print('[종목코드 : %s, 종목명 : %s] 가격 정보 파일 존재' % (str(f_code), str(f_name)))

[종목코드 : 005930, 종목명 : 삼성전자] 가격 정보 저장 완료
[종목코드 : 000660, 종목명 : SK하이닉스] 가격 정보 저장 완료
[종목코드 : 035420, 종목명 : NAVER] 가격 정보 저장 완료
[종목코드 : 035720, 종목명 : 카카오] 가격 정보 저장 완료
[종목코드 : 207940, 종목명 : 삼성바이오로직스] 가격 정보 저장 완료
[종목코드 : 005935, 종목명 : 삼성전자우] 가격 정보 저장 완료
[종목코드 : 051910, 종목명 : LG화학] 가격 정보 저장 완료
[종목코드 : 006400, 종목명 : 삼성SDI] 가격 정보 저장 완료
[종목코드 : 005380, 종목명 : 현대차] 가격 정보 저장 완료
[종목코드 : 068270, 종목명 : 셀트리온] 가격 정보 저장 완료
[종목코드 : 000270, 종목명 : 기아] 가격 정보 저장 완료
[종목코드 : 005490, 종목명 : POSCO] 가격 정보 저장 완료
[종목코드 : 066570, 종목명 : LG전자] 가격 정보 저장 완료
[종목코드 : 028260, 종목명 : 삼성물산] 가격 정보 저장 완료
[종목코드 : 012330, 종목명 : 현대모비스] 가격 정보 저장 완료
[종목코드 : 096770, 종목명 : SK이노베이션] 가격 정보 저장 완료
[종목코드 : 051900, 종목명 : LG생활건강] 가격 정보 저장 완료
[종목코드 : 017670, 종목명 : SK텔레콤] 가격 정보 저장 완료
[종목코드 : 105560, 종목명 : KB금융] 가격 정보 저장 완료
[종목코드 : 055550, 종목명 : 신한지주] 가격 정보 저장 완료
[종목코드 : 034730, 종목명 : SK] 가격 정보 저장 완료
[종목코드 : 036570, 종목명 : 엔씨소프트] 가격 정보 저장 완료
[종목코드 : 011200, 종목명 : HMM] 가격 정보 저장 완료
[종목코드 : 015760, 종목명 : 한국전력] 가격 정보 저장 완료
[종목코드 : 032830, 종목명 : 삼성생명] 가격 정보 저장 완료
[종목코드 : 018260, 종목명 : 삼성에스디에스] 가격 정보 저장 완료
[종목코드 : 009150, 종목명 : 삼성전기] 가격 정보 저장 완료
[종목코드 : 090430, 종목명 : 아모레퍼시픽] 가격 정보 저장 완료
[종목코드 : 086790, 종목명 : 하나금융지주] 가격 정보 저장 완료
[종목코드 : 251270, 종목명 : 넷마블] 가격 정보 저장 완료
[종목코드 : 003670, 종목명 : 포스코케미칼] 가격 정보 저장 완료
[종목코드 : 352820, 종목명 : 하이브] 가격 정보 저장 완료
[종목코드 : 034020, 종목명 : 두산중공업] 가격 정보 저장 완료
[종목코드 : 010950, 종목명 : S-Oil] 가격 정보 저장 완료
[종목코드 : 033780, 종목명 : KT&G] 가격 정보 저장 완료
[종목코드 : 003490, 종목명 : 대한항공] 가격 정보 저장 완료
[종목코드 : 000810, 종목명 : 삼성화재] 가격 정보 저장 완료
[종목코드 : 010130, 종목명 : 고려아연] 가격 정보 저장 완료
[종목코드 : 009540, 종목명 : 한국조선해양] 가격 정보 저장 완료
[종목코드 : 326030, 종목명 : SK바이오팜] 가격 정보 저장 완료
[종목코드 : 011170, 종목명 : 롯데케미칼] 가격 정보 저장 완료
[종목코드 : 030200, 종목명 : KT] 가격 정보 저장 완료
[종목코드 : 018880, 종목명 : 한온시스템] 가격 정보 저장 완료
[종목코드 : 034220, 종목명 : LG디스플레이] 가격 정보 저장 완료
[종목코드 : 316140, 종목명 : 우리금융지주] 가격 정보 저장 완료
[종목코드 : 009830, 종목명 : 한화솔루션] 가격 정보 저장 완료
[종목코드 : 024110, 종목명 : 기업은행] 가격 정보 저장 완료
[종목코드 : 086280, 종목명 : 현대글로비스] 가격 정보 저장 완료
[종목코드 : 004020, 종목명 : 현대제철] 가격 정보 저장 완료
[종목코드 : 097950, 종목명 : CJ제일제당] 가격 정보 저장 완료
[종목코드 : 032640, 종목명 : LG유플러스] 가격 정보 저장 완료
[종목코드 : 011780, 종목명 : 금호석유] 가격 정보 저장 완료
[종목코드 : 021240, 종목명 : 코웨이] 가격 정보 저장 완료
[종목코드 : 000720, 종목명 : 현대건설] 가격 정보 저장 완료
[종목코드 : 161390, 종목명 : 한국타이어앤테크놀로지] 가격 정보 저장 완료
[종목코드 : 006800, 종목명 : 미래에셋증권] 가격 정보 저장 완료
[종목코드 : 035250, 종목명 : 강원랜드] 가격 정보 저장 완료
[종목코드 : 071050, 종목명 : 한국금융지주] 가격 정보 저장 완료
[종목코드 : 267250, 종목명 : 현대중공업지주] 가격 정보 저장 완료
[종목코드 : 011070, 종목명 : LG이노텍] 가격 정보 저장 완료
[종목코드 : 008930, 종목명 : 한미사이언스] 가격 정보 저장 완료
[종목코드 : 002790, 종목명 : 아모레G] 가격 정보 저장 완료
[종목코드 : 028050, 종목명 : 삼성엔지니어링] 가격 정보 저장 완료
[종목코드 : 139480, 종목명 : 이마트] 가격 정보 저장 완료
[종목코드 : 271560, 종목명 : 오리온] 가격 정보 저장 완료
[종목코드 : 241560, 종목명 : 두산밥캣] 가격 정보 저장 완료
[종목코드 : 180640, 종목명 : 한진칼] 가격 정보 저장 완료
[종목코드 : 000100, 종목명 : 유한양행] 가격 정보 저장 완료
[종목코드 : 069500, 종목명 : KODEX 200] 가격 정보 저장 완료
[종목코드 : 000120, 종목명 : CJ대한통운] 가격 정보 저장 완료
[종목코드 : 078930, 종목명 : GS] 가격 정보 저장 완료
[종목코드 : 003410, 종목명 : 쌍용C&E] 가격 정보 저장 완료
[종목코드 : 029780, 종목명 : 삼성카드] 가격 정보 저장 완료
[종목코드 : 028670, 종목명 : 팬오션] 가격 정보 저장 완료
[종목코드 : 004990, 종목명 : 롯데지주] 가격 정보 저장 완료
[종목코드 : 005830, 종목명 : DB손해보험] 가격 정보 저장 완료
[종목코드 : 016360, 종목명 : 삼성증권] 가격 정보 저장 완료
[종목코드 : 128940, 종목명 : 한미약품] 가격 정보 저장 완료
[종목코드 : 005387, 종목명 : 현대차2우B] 가격 정보 저장 완료
[종목코드 : 298020, 종목명 : 효성티앤씨] 가격 정보 저장 완료
[종목코드 : 006360, 종목명 : GS건설] 가격 정보 저장 완료
[종목코드 : 020150, 종목명 : 일진머티리얼즈] 가격 정보 저장 완료
[종목코드 : 007070, 종목명 : GS리테일] 가격 정보 저장 완료
[종목코드 : 008770, 종목명 : 호텔신라] 가격 정보 저장 완료
[종목코드 : 005940, 종목명 : NH투자증권] 가격 정보 저장 완료
[종목코드 : 112610, 종목명 : 씨에스윈드] 가격 정보 저장 완료
[종목코드 : 042660, 종목명 : 대우조선해양] 가격 정보 저장 완료
[종목코드 : 307950, 종목명 : 현대오토에버] 가격 정보 저장 완료
[종목코드 : 006280, 종목명 : 녹십자] 가격 정보 저장 완료
[종목코드 : 008560, 종목명 : 메리츠증권] 가격 정보 저장 완료
[종목코드 : 019170, 종목명 : 신풍제약] 가격 정보 저장 완료
[종목코드 : 010620, 종목명 : 현대미포조선] 가격 정보 저장 완료
[종목코드 : 036460, 종목명 : 한국가스공사] 가격 정보 저장 완료
[종목코드 : 047050, 종목명 : 포스코인터내셔널] 가격 정보 저장 완료
[종목코드 : 047810, 종목명 : 한국항공우주] 가격 정보 저장 완료
[종목코드 : 138040, 종목명 : 메리츠금융지주] 가격 정보 저장 완료
[종목코드 : 336260, 종목명 : 두산퓨얼셀] 가격 정보 저장 완료
[종목코드 : 081660, 종목명 : 휠라홀딩스] 가격 정보 저장 완료
[종목코드 : 272210, 종목명 : 한화시스템] 가격 정보 저장 완료
[종목코드 : 023530, 종목명 : 롯데쇼핑] 가격 정보 저장 완료
[종목코드 : 039490, 종목명 : 키움증권] 가격 정보 저장 완료
[종목코드 : 047040, 종목명 : 대우건설] 가격 정보 저장 완료
[종목코드 : 012750, 종목명 : 에스원] 가격 정보 저장 완료
[종목코드 : 026960, 종목명 : 동서] 가격 정보 저장 완료
[종목코드 : 010060, 종목명 : OCI] 가격 정보 저장 완료
[종목코드 : 088350, 종목명 : 한화생명] 가격 정보 저장 완료
[종목코드 : 014680, 종목명 : 한솔케미칼] 가격 정보 저장 완료
[종목코드 : 002380, 종목명 : KCC] 가격 정보 저장 완료
[종목코드 : 051915, 종목명 : LG화학우] 가격 정보 저장 완료
[종목코드 : 000060, 종목명 : 메리츠화재] 가격 정보 저장 완료
[종목코드 : 285130, 종목명 : SK케미칼] 가격 정보 저장 완료
[종목코드 : 204320, 종목명 : 만도] 가격 정보 저장 완료
[종목코드 : 030000, 종목명 : 제일기획] 가격 정보 저장 완료
[종목코드 : 282330, 종목명 : BGF리테일] 가격 정보 저장 완료
[종목코드 : 009240, 종목명 : 한샘] 가격 정보 저장 완료
[종목코드 : 000990, 종목명 : DB하이텍] 가격 정보 저장 완료
[종목코드 : 298050, 종목명 : 효성첨단소재] 가격 정보 저장 완료
[종목코드 : 004170, 종목명 : 신세계] 가격 정보 저장 완료
[종목코드 : 064350, 종목명 : 현대로템] 가격 정보 저장 완료
[종목코드 : 005385, 종목명 : 현대차우] 가격 정보 저장 완료
[종목코드 : 011210, 종목명 : 현대위아] 가격 정보 저장 완료
[종목코드 : 012510, 종목명 : 더존비즈온] 가격 정보 저장 완료
[종목코드 : 012450, 종목명 : 한화에어로스페이스] 가격 정보 저장 완료
[종목코드 : 004800, 종목명 : 효성] 가격 정보 저장 완료
[종목코드 : 138930, 종목명 : BNK금융지주] 가격 정보 저장 완료
[종목코드 : 153130, 종목명 : KODEX 단기채권] 가격 정보 저장 완료
[종목코드 : 000080, 종목명 : 하이트진로] 가격 정보 저장 완료
[종목코드 : 006260, 종목명 : LS] 가격 정보 저장 완료
[종목코드 : 001450, 종목명 : 현대해상] 가격 정보 저장 완료
[종목코드 : 000880, 종목명 : 한화] 가격 정보 저장 완료
[종목코드 : 001440, 종목명 : 대한전선] 가격 정보 저장 완료
[종목코드 : 252670, 종목명 : KODEX 200선물인버스2X] 가격 정보 저장 완료
[종목코드 : 120110, 종목명 : 코오롱인더] 가격 정보 저장 완료
[종목코드 : 017800, 종목명 : 현대엘리베이] 가격 정보 저장 완료
[종목코드 : 102110, 종목명 : TIGER 200] 가격 정보 저장 완료
[종목코드 : 003090, 종목명 : 대웅] 가격 정보 저장 완료
[종목코드 : 052690, 종목명 : 한전기술] 가격 정보 저장 완료
[종목코드 : 011000, 종목명 : 진원생명과학] 가격 정보 저장 완료
[종목코드 : 294870, 종목명 : HDC현대산업개발] 가격 정보 저장 완료
[종목코드 : 001230, 종목명 : 동국제강] 가격 정보 저장 완료
[종목코드 : 004370, 종목명 : 농심] 가격 정보 저장 완료
[종목코드 : 073240, 종목명 : 금호타이어] 가격 정보 저장 완료
[종목코드 : 007310, 종목명 : 오뚜기] 가격 정보 저장 완료
[종목코드 : 051600, 종목명 : 한전KPS] 가격 정보 저장 완료
[종목코드 : 010120, 종목명 : LS ELECTRIC] 가격 정보 저장 완료
[종목코드 : 069620, 종목명 : 대웅제약] 가격 정보 저장 완료
[종목코드 : 069960, 종목명 : 현대백화점] 가격 정보 저장 완료
[종목코드 : 042700, 종목명 : 한미반도체] 가격 정보 저장 완료
[종목코드 : 004000, 종목명 : 롯데정밀화학] 가격 정보 저장 완료
[종목코드 : 102780, 종목명 : KODEX 삼성그룹] 가격 정보 저장 완료
[종목코드 : 336370, 종목명 : 솔루스첨단소재] 가격 정보 저장 완료
[종목코드 : 111770, 종목명 : 영원무역] 가격 정보 저장 완료
[종목코드 : 006650, 종목명 : 대한유화] 가격 정보 저장 완료
[종목코드 : 000240, 종목명 : 한국앤컴퍼니] 가격 정보 저장 완료
[종목코드 : 010780, 종목명 : 아이에스동서] 가격 정보 저장 완료
[종목코드 : 016380, 종목명 : KG동부제철] 가격 정보 저장 완료
[종목코드 : 000150, 종목명 : 두산] 가격 정보 저장 완료
[종목코드 : 009900, 종목명 : 명신산업] 가격 정보 저장 완료
[종목코드 : 013890, 종목명 : 지누스] 가격 정보 저장 완료
[종목코드 : 005850, 종목명 : 에스엘] 가격 정보 저장 완료
[종목코드 : 001740, 종목명 : SK네트웍스] 가격 정보 저장 완료
[종목코드 : 139130, 종목명 : DGB금융지주] 가격 정보 저장 완료
[종목코드 : 181710, 종목명 : NHN] 가격 정보 저장 완료
[종목코드 : 175330, 종목명 : JB금융지주] 가격 정보 저장 완료
[종목코드 : 005250, 종목명 : 녹십자홀딩스] 가격 정보 저장 완료
[종목코드 : 185750, 종목명 : 종근당] 가격 정보 저장 완료
[종목코드 : 003000, 종목명 : 부광약품] 가격 정보 저장 완료
[종목코드 : 051905, 종목명 : LG생활건강우] 가격 정보 저장 완료
[종목코드 : 330590, 종목명 : 롯데리츠] 가격 정보 저장 완료
[종목코드 : 192820, 종목명 : 코스맥스] 가격 정보 저장 완료
[종목코드 : 214980, 종목명 : KODEX 단기채권PLUS] 가격 정보 저장 완료
[종목코드 : 122630, 종목명 : KODEX 레버리지] 가격 정보 저장 완료
[종목코드 : 031430, 종목명 : 신세계인터내셔날] 가격 정보 저장 완료
[종목코드 : 273130, 종목명 : KODEX 종합채권(AA-이상)액티브] 가격 정보 저장 완료
[종목코드 : 032350, 종목명 : 롯데관광개발] 가격 정보 저장 완료
[종목코드 : 066575, 종목명 : LG전자우] 가격 정보 저장 완료
[종목코드 : 363280, 종목명 : 티와이홀딩스] 가격 정보 저장 완료
[종목코드 : 298000, 종목명 : 효성화학] 가격 정보 저장 완료
[종목코드 : 278530, 종목명 : KODEX 200TR] 가격 정보 저장 완료
[종목코드 : 000670, 종목명 : 영풍] 가격 정보 저장 완료
[종목코드 : 292150, 종목명 : TIGER TOP10] 가격 정보 저장 완료
[종목코드 : 161890, 종목명 : 한국콜마] 가격 정보 저장 완료
[종목코드 : 005300, 종목명 : 롯데칠성] 가격 정보 저장 완료
[종목코드 : 004490, 종목명 : 세방전지] 가격 정보 저장 완료
[종목코드 : 214320, 종목명 : 이노션] 가격 정보 저장 완료
[종목코드 : 091990, 종목명 : 셀트리온헬스케어] 가격 정보 저장 완료
[종목코드 : 293490, 종목명 : 카카오게임즈] 가격 정보 저장 완료
[종목코드 : 247540, 종목명 : 에코프로비엠] 가격 정보 저장 완료
[종목코드 : 068760, 종목명 : 셀트리온제약] 가격 정보 저장 완료
[종목코드 : 263750, 종목명 : 펄어비스] 가격 정보 저장 완료
[종목코드 : 036490, 종목명 : SK머티리얼즈] 가격 정보 저장 완료
[종목코드 : 028300, 종목명 : 에이치엘비] 가격 정보 저장 완료
[종목코드 : 096530, 종목명 : 씨젠] 가격 정보 저장 완료
[종목코드 : 035760, 종목명 : CJ ENM] 가격 정보 저장 완료
[종목코드 : 196170, 종목명 : 알테오젠] 가격 정보 저장 완료
[종목코드 : 066970, 종목명 : 엘앤에프] 가격 정보 저장 완료
[종목코드 : 145020, 종목명 : 휴젤] 가격 정보 저장 완료
[종목코드 : 253450, 종목명 : 스튜디오드래곤] 가격 정보 저장 완료
[종목코드 : 058470, 종목명 : 리노공업] 가격 정보 저장 완료
[종목코드 : 357780, 종목명 : 솔브레인] 가격 정보 저장 완료
[종목코드 : 240810, 종목명 : 원익IPS] 가격 정보 저장 완료
[종목코드 : 064760, 종목명 : 티씨케이] 가격 정보 저장 완료
[종목코드 : 278280, 종목명 : 천보] 가격 정보 저장 완료
[종목코드 : 032500, 종목명 : 케이엠더블유] 가격 정보 저장 완료
[종목코드 : 095700, 종목명 : 제넥신] 가격 정보 저장 완료
[종목코드 : 108320, 종목명 : LX세미콘] 가격 정보 저장 완료
[종목코드 : 237690, 종목명 : 에스티팜] 가격 정보 저장 완료
[종목코드 : 007390, 종목명 : 네이처셀] 가격 정보 저장 완료
[종목코드 : 098460, 종목명 : 고영] 가격 정보 저장 완료
[종목코드 : 048260, 종목명 : 오스템임플란트] 가격 정보 저장 완료
[종목코드 : 178920, 종목명 : PI첨단소재] 가격 정보 저장 완료
[종목코드 : 034230, 종목명 : 파라다이스] 가격 정보 저장 완료
[종목코드 : 005290, 종목명 : 동진쎄미켐] 가격 정보 저장 완료
[종목코드 : 025900, 종목명 : 동화기업] 가격 정보 저장 완료
[종목코드 : 067160, 종목명 : 아프리카TV] 가격 정보 저장 완료
[종목코드 : 078340, 종목명 : 컴투스] 가격 정보 저장 완료
[종목코드 : 030190, 종목명 : NICE평가정보] 가격 정보 저장 완료
[종목코드 : 056190, 종목명 : 에스에프에이] 가격 정보 저장 완료
[종목코드 : 268600, 종목명 : 셀리버리] 가격 정보 저장 완료
[종목코드 : 041510, 종목명 : 에스엠] 가격 정보 저장 완료
[종목코드 : 085660, 종목명 : 차바이오텍] 가격 정보 저장 완료
[종목코드 : 035900, 종목명 : JYP Ent.] 가격 정보 저장 완료
[종목코드 : 214150, 종목명 : 클래시스] 가격 정보 저장 완료
[종목코드 : 200130, 종목명 : 콜마비앤에이치] 가격 정보 저장 완료
[종목코드 : 039030, 종목명 : 이오테크닉스] 가격 정보 저장 완료
[종목코드 : 213420, 종목명 : 덕산네오룩스] 가격 정보 저장 완료
[종목코드 : 141080, 종목명 : 레고켐바이오] 가격 정보 저장 완료
[종목코드 : 060250, 종목명 : NHN한국사이버결제] 가격 정보 저장 완료
[종목코드 : 086900, 종목명 : 메디톡스] 가격 정보 저장 완료
[종목코드 : 206650, 종목명 : 유바이오로직스] 가격 정보 저장 완료
[종목코드 : 235980, 종목명 : 메드팩토] 가격 정보 저장 완료
[종목코드 : 323990, 종목명 : 박셀바이오] 가격 정보 저장 완료
[종목코드 : 022100, 종목명 : 포스코 ICT] 가격 정보 저장 완료
[종목코드 : 140410, 종목명 : 메지온] 가격 정보 저장 완료
[종목코드 : 036540, 종목명 : SFA반도체] 가격 정보 저장 완료
[종목코드 : 000250, 종목명 : 삼천당제약] 가격 정보 저장 완료
[종목코드 : 048410, 종목명 : 현대바이오] 가격 정보 저장 완료
[종목코드 : 086450, 종목명 : 동국제약] 가격 정보 저장 완료
[종목코드 : 084850, 종목명 : 아이티엠반도체] 가격 정보 저장 완료
[종목코드 : 046890, 종목명 : 서울반도체] 가격 정보 저장 완료
[종목코드 : 084370, 종목명 : 유진테크] 가격 정보 저장 완료
[종목코드 : 950130, 종목명 : 엑세스바이오] 가격 정보 저장 완료
[종목코드 : 069080, 종목명 : 웹젠] 가격 정보 저장 완료
[종목코드 : 299660, 종목명 : 셀리드] 가격 정보 저장 완료
[종목코드 : 039200, 종목명 : 오스코텍] 가격 정보 저장 완료
[종목코드 : 166090, 종목명 : 하나머티리얼즈] 가격 정보 저장 완료
[종목코드 : 144510, 종목명 : 녹십자랩셀] 가격 정보 저장 완료
[종목코드 : 122870, 종목명 : 와이지엔터테인먼트] 가격 정보 저장 완료
[종목코드 : 218410, 종목명 : RFHIC] 가격 정보 저장 완료
[종목코드 : 067630, 종목명 : 에이치엘비생명과학] 가격 정보 저장 완료
[종목코드 : 112040, 종목명 : 위메이드] 가격 정보 저장 완료
[종목코드 : 215200, 종목명 : 메가스터디교육] 가격 정보 저장 완료
[종목코드 : 084990, 종목명 : 헬릭스미스] 가격 정보 저장 완료
[종목코드 : 298380, 종목명 : 에이비엘바이오] 가격 정보 저장 완료
[종목코드 : 151910, 종목명 : 나노스] 가격 정보 저장 완료
[종목코드 : 194480, 종목명 : 데브시스터즈] 가격 정보 저장 완료
[종목코드 : 025980, 종목명 : 아난티] 가격 정보 저장 완료
[종목코드 : 064550, 종목명 : 바이오니아] 가격 정보 저장 완료
[종목코드 : 003380, 종목명 : 하림지주] 가격 정보 저장 완료
[종목코드 : 215000, 종목명 : 골프존] 가격 정보 저장 완료
[종목코드 : 033640, 종목명 : 네패스] 가격 정보 저장 완료
[종목코드 : 078600, 종목명 : 대주전자재료] 가격 정보 저장 완료
[종목코드 : 217270, 종목명 : 넵튠] 가격 정보 저장 완료
[종목코드 : 089980, 종목명 : 상아프론테크] 가격 정보 저장 완료
[종목코드 : 214450, 종목명 : 파마리서치] 가격 정보 저장 완료
[종목코드 : 140860, 종목명 : 파크시스템스] 가격 정보 저장 완료
[종목코드 : 230360, 종목명 : 에코마케팅] 가격 정보 저장 완료
[종목코드 : 027360, 종목명 : 아주IB투자] 가격 정보 저장 완료
[종목코드 : 222800, 종목명 : 심텍] 가격 정보 저장 완료
[종목코드 : 082270, 종목명 : 젬백스] 가격 정보 저장 완료
[종목코드 : 131290, 종목명 : 티에스이] 가격 정보 저장 완료
[종목코드 : 088800, 종목명 : 에이스테크] 가격 정보 저장 완료
[종목코드 : 074600, 종목명 : 원익QnC] 가격 정보 저장 완료
[종목코드 : 293780, 종목명 : 압타바이오] 가격 정보 저장 완료
[종목코드 : 185490, 종목명 : 아이진] 가격 정보 저장 완료
[종목코드 : 178320, 종목명 : 서진시스템] 가격 정보 저장 완료
[종목코드 : 036830, 종목명 : 솔브레인홀딩스] 가격 정보 저장 완료
[종목코드 : 084110, 종목명 : 휴온스글로벌] 가격 정보 저장 완료
[종목코드 : 151860, 종목명 : KG ETS] 가격 정보 저장 완료
[종목코드 : 092040, 종목명 : 아미코젠] 가격 정보 저장 완료
[종목코드 : 131970, 종목명 : 테스나] 가격 정보 저장 완료
[종목코드 : 048530, 종목명 : 인트론바이오] 가격 정보 저장 완료
[종목코드 : 039840, 종목명 : 디오] 가격 정보 저장 완료
[종목코드 : 290650, 종목명 : 엘앤씨바이오] 가격 정보 저장 완료
[종목코드 : 041960, 종목명 : 코미팜] 가격 정보 저장 완료
[종목코드 : 065660, 종목명 : 안트로젠] 가격 정보 저장 완료
[종목코드 : 214370, 종목명 : 케어젠] 가격 정보 저장 완료
[종목코드 : 272290, 종목명 : 이녹스첨단소재] 가격 정보 저장 완료
[종목코드 : 183490, 종목명 : 엔지켐생명과학] 가격 정보 저장 완료
[종목코드 : 035080, 종목명 : 인터파크] 가격 정보 저장 완료
[종목코드 : 036930, 종목명 : 주성엔지니어링] 가격 정보 저장 완료
[종목코드 : 101490, 종목명 : 에스앤에스텍] 가격 정보 저장 완료
[종목코드 : 294090, 종목명 : 이오플로우] 가격 정보 저장 완료
[종목코드 : 053800, 종목명 : 안랩] 가격 정보 저장 완료
[종목코드 : 256840, 종목명 : 한국비엔씨] 가격 정보 저장 완료
[종목코드 : 078130, 종목명 : 국일제지] 가격 정보 저장 완료
[종목코드 : 205470, 종목명 : 휴마시스] 가격 정보 저장 완료
[종목코드 : 058820, 종목명 : CMG제약] 가격 정보 저장 완료
[종목코드 : 243070, 종목명 : 휴온스] 가격 정보 저장 완료
[종목코드 : 299900, 종목명 : 위지윅스튜디오] 가격 정보 저장 완료
[종목코드 : 222080, 종목명 : 씨아이에스] 가격 정보 저장 완료
[종목코드 : 052400, 종목명 : 코나아이] 가격 정보 저장 완료
[종목코드 : 090460, 종목명 : 비에이치] 가격 정보 저장 완료
[종목코드 : 183300, 종목명 : 코미코] 가격 정보 저장 완료
[종목코드 : 104480, 종목명 : 티케이케미칼] 가격 정보 저장 완료
[종목코드 : 033290, 종목명 : 코웰패션] 가격 정보 저장 완료
[종목코드 : 290510, 종목명 : 코리아센터] 가격 정보 저장 완료
[종목코드 : 041190, 종목명 : 우리기술투자] 가격 정보 저장 완료
[종목코드 : 226950, 종목명 : 올릭스] 가격 정보 저장 완료
[종목코드 : 092190, 종목명 : 서울바이오시스] 가격 정보 저장 완료
[종목코드 : 100090, 종목명 : 삼강엠앤티] 가격 정보 저장 완료
[종목코드 : 319660, 종목명 : 피에스케이] 가격 정보 저장 완료
[종목코드 : 035600, 종목명 : KG이니시스] 가격 정보 저장 완료
[종목코드 : 038500, 종목명 : 삼표시멘트] 가격 정보 저장 완료
[종목코드 : 042000, 종목명 : 카페24] 가격 정보 저장 완료
[종목코드 : 030520, 종목명 : 한글과컴퓨터] 가격 정보 저장 완료
[종목코드 : 053030, 종목명 : 바이넥스] 가격 정보 저장 완료
[종목코드 : 267980, 종목명 : 매일유업] 가격 정보 저장 완료
[종목코드 : 137400, 종목명 : 피엔티] 가격 정보 저장 완료
[종목코드 : 068240, 종목명 : 다원시스] 가격 정보 저장 완료
[종목코드 : 216080, 종목명 : 제테마] 가격 정보 저장 완료
[종목코드 : 013120, 종목명 : 동원개발] 가격 정보 저장 완료
[종목코드 : 095660, 종목명 : 네오위즈] 가격 정보 저장 완료
[종목코드 : 060150, 종목명 : 인선이엔티] 가격 정보 저장 완료
[종목코드 : 061970, 종목명 : 엘비세미콘] 가격 정보 저장 완료
[종목코드 : 095610, 종목명 : 테스] 가격 정보 저장 완료
[종목코드 : 089970, 종목명 : 에이피티씨] 가격 정보 저장 완료
[종목코드 : 036810, 종목명 : 에프에스티] 가격 정보 저장 완료
[종목코드 : 348210, 종목명 : 넥스틴] 가격 정보 저장 완료
[종목코드 : 330860, 종목명 : 네패스아크] 가격 정보 저장 완료
[종목코드 : 263720, 종목명 : 디앤씨미디어] 가격 정보 저장 완료
[종목코드 : 143240, 종목명 : 사람인에이치알] 가격 정보 저장 완료
[종목코드 : 091700, 종목명 : 파트론] 가격 정보 저장 완료
[종목코드 : 067000, 종목명 : 조이시티] 가격 정보 저장 완료
[종목코드 : 204270, 종목명 : 제이앤티씨] 가격 정보 저장 완료
[종목코드 : 032190, 종목명 : 다우데이타] 가격 정보 저장 완료
[종목코드 : 131370, 종목명 : 알서포트] 가격 정보 저장 완료
[종목코드 : 321550, 종목명 : 티움바이오] 가격 정보 저장 완료
[종목코드 : 347860, 종목명 : 알체라] 가격 정보 저장 완료
[종목코드 : 003800, 종목명 : 에이스침대] 가격 정보 저장 완료
[종목코드 : 032300, 종목명 : 한국파마] 가격 정보 저장 완료
[종목코드 : 122450, 종목명 : KMH] 가격 정보 저장 완료
[종목코드 : 206640, 종목명 : 바디텍메드] 가격 정보 저장 완료
[종목코드 : 015750, 종목명 : 성우하이텍] 가격 정보 저장 완료
[종목코드 : 060720, 종목명 : KH바텍] 가격 정보 저장 완료
[종목코드 : 043150, 종목명 : 바텍] 가격 정보 저장 완료
[종목코드 : 006730, 종목명 : 서부T&D] 가격 정보 저장 완료
[종목코드 : 089030, 종목명 : 테크윙] 가격 정보 저장 완료
[종목코드 : 348150, 종목명 : 고바이오랩] 가격 정보 저장 완료
[종목코드 : 319400, 종목명 : 현대무벡스] 가격 정보 저장 완료
[종목코드 : 232140, 종목명 : 와이아이케이] 가격 정보 저장 완료
[종목코드 : 083790, 종목명 : 크리스탈지노믹스] 가격 정보 저장 완료
[종목코드 : 299030, 종목명 : 하나기술] 가격 정보 저장 완료
[종목코드 : 049070, 종목명 : 인탑스] 가격 정보 저장 완료
[종목코드 : 067310, 종목명 : 하나마이크론] 가격 정보 저장 완료
[종목코드 : 036030, 종목명 : 케이티알파] 가격 정보 저장 완료
[종목코드 : 031390, 종목명 : 녹십자셀] 가격 정보 저장 완료
[종목코드 : 121800, 종목명 : 비덴트] 가격 정보 저장 완료
[종목코드 : 033310, 종목명 : 엠투엔] 가격 정보 저장 완료
[종목코드 : 086390, 종목명 : 유니테스트] 가격 정보 저장 완료
[종목코드 : 078020, 종목명 : 이베스트투자증권] 가격 정보 저장 완료
[종목코드 : 102710, 종목명 : 이엔에프테크놀로지] 가격 정보 저장 완료
[종목코드 : 314130, 종목명 : 지놈앤컴퍼니] 가격 정보 저장 완료
[종목코드 : 035890, 종목명 : 서희건설] 가격 정보 저장 완료
[종목코드 : 032620, 종목명 : 유비케어] 가격 정보 저장 완료
[종목코드 : 220630, 종목명 : 맘스터치] 가격 정보 저장 완료
[종목코드 : 064260, 종목명 : 다날] 가격 정보 저장 완료
[종목코드 : 287410, 종목명 : 제이시스메디칼] 가격 정보 저장 완료
[종목코드 : 110790, 종목명 : 크리스에프앤씨] 가격 정보 저장 완료
[종목코드 : 099320, 종목명 : 쎄트렉아이] 가격 정보 저장 완료

In [9]:
# Zip the files from given directory that matches the filter
def zipFilesInDir(dirName, zipFileName, filter):
   # create a ZipFile object
   with ZipFile(zipFileName, 'w') as zipObj:
       # Iterate over all the files in directory
       for folderName, subfolders, filenames in os.walk(dirName):
           for filename in filenames:
               if filter(filename):
                   # create complete filepath of file in directory
                   filePath = os.path.join(folderName, filename)
                   # Add file to zip
                   zipObj.write(filePath, basename(filePath))

In [10]:
zipFilesInDir('price', 'price2.zip', lambda name : 'csv' in name)

In [413]:
pd_price = pd.read_csv('price/000670_price.csv')

In [414]:
pd_price

           Date    Open    High     Low   Close  Volume    Change
0    2020-01-02  645000  653000  632000  646000    1065  0.001550
1    2020-01-03  647000  664000  641000  658000    1431  0.018576
2    2020-01-06  647000  659000  643000  652000    1018 -0.009119
3    2020-01-07  652000  666000  647000  658000    1338  0.009202
4    2020-01-08  644000  651000  636000  644000    1336 -0.021277
..          ...     ...     ...     ...     ...     ...       ...
466  2021-11-19  648000  655000  637000  650000    2720 -0.001536
467  2021-11-22  650000  665000  643000  665000     929  0.023077
468  2021-11-23  664000  664000  650000  650000     984 -0.022556
469  2021-11-24  645000  652000  641000  647000     859 -0.004615
470  2021-11-25  645000  655000  642000  647000     554  0.000000

[471 rows x 7 columns]

In [415]:
start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
Business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [416]:
print(f'WEEKDAY of "start_date" : {start_weekday}')
print(f'NUM of WEEKS to "end_date" : {max_weeknum}')
print(f'HOW MANY "Business_days" : {Business_days.shape}', )
print(Business_days.head())

WEEKDAY of "start_date" : 2
NUM of WEEKS to "end_date" : 47
HOW MANY "Business_days" : (497, 1)
        Date
0 2020-01-01
1 2020-01-02
2 2020-01-03
3 2020-01-06
4 2020-01-07

In [417]:
pd_price['weekday'] = pd_price.Date.apply(lambda x: pd.to_datetime(x).weekday())

In [418]:
# 1년치로 데이터 생성되기 때문에 이를 바로 잡아야 함.(주수는 1년만다 반복됨. 따라서 동일한 값이 2번 들어감)
#pd_total_price_data['weeknum'] = pd_total_price_data.Date.apply(lambda x: pd.to_datetime(x).strftime('%V'))

last_weeknum = 0

pd_price['weeknum'] = 0

for d_index in range(0, pd_price.shape[0]):
  now_date = pd_price['Date'].values[d_index]
  if pd.to_datetime(start_date).year == pd.to_datetime(now_date).year:
      last_weeknum = int(pd.to_datetime(now_date).strftime('%V'))
      pd_price['weeknum'].values[d_index] = last_weeknum
  else:
      pd_price['weeknum'].values[d_index] = int(last_weeknum) + int(pd.to_datetime(now_date).strftime('%V'))

In [419]:
pd_price['weekday'].values[0]

3

In [420]:
while int(pd_price['weekday'].values[0]) != 0:
  pd_price.drop(index=pd_price.index[0], axis=0, inplace=True)

pd_price = pd_price.reset_index(drop=True)

In [421]:
pd_price.head(10)

         Date    Open    High     Low  ...  Volume    Change  weekday  weeknum
0  2020-01-06  647000  659000  643000  ...    1018 -0.009119        0        2
1  2020-01-07  652000  666000  647000  ...    1338  0.009202        1        2
2  2020-01-08  644000  651000  636000  ...    1336 -0.021277        2        2
3  2020-01-09  636000  659000  636000  ...    1520  0.023292        3        2
4  2020-01-10  650000  663000  645000  ...    1402 -0.004552        4        2
5  2020-01-13  647000  663000  646000  ...    1471  0.003049        0        3
6  2020-01-14  658000  664000  647000  ...    1917 -0.001520        1        3
7  2020-01-15  653000  668000  653000  ...     741  0.013699        2        3
8  2020-01-16  669000  680000  661000  ...    1222  0.021021        3        3
9  2020-01-17  677000  685000  671000  ...     974 -0.013235        4        3

[10 rows x 9 columns]

In [422]:
pd_price.shape

(469, 9)

In [423]:
pd_price['week_diff'] = 0

In [424]:
for d_index in range(0, pd_price.shape[0]-5):
  #print(d_index, (pd_price['Close'].values[d_index+5] - pd_price['Close'].values[d_index]))
  pd_price['week_diff'].values[d_index] = (pd_price['Close'].values[d_index+5] - pd_price['Close'].values[d_index])

In [425]:
def get_sma_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        sma_column_name = str('SMA_') + str(period)
        pd_stock_price[sma_column_name] = pd_stock_price['Close'].rolling(window=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[sma_column_name] = pd_stock_price[sma_column_name].round(2)

    print(pd_stock_price.head(10))

    return pd_stock_price

In [426]:
pd_price = get_sma_index(pd_price, [5, 10, 20, 30])

         Date    Open    High  ...     SMA_10     SMA_20     SMA_30
0  2020-01-06  647000  659000  ...        NaN        NaN        NaN
1  2020-01-07  652000  666000  ...        NaN        NaN        NaN
2  2020-01-08  644000  651000  ...        NaN        NaN        NaN
3  2020-01-09  636000  659000  ...        NaN        NaN        NaN
4  2020-01-10  650000  663000  ...  653800.00  653800.00  653800.00
5  2020-01-13  647000  663000  ...  654500.00  654500.00  654500.00
6  2020-01-14  658000  664000  ...  654857.14  654857.14  654857.14
7  2020-01-15  653000  668000  ...  656250.00  656250.00  656250.00
8  2020-01-16  669000  680000  ...  658888.89  658888.89  658888.89
9  2020-01-17  677000  685000  ...  660100.00  660100.00  660100.00

[10 rows x 14 columns]

In [427]:
def get_ema_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        ema_column_name = str('EMA_') + str(period)
        pd_stock_price[ema_column_name] = pd_stock_price['Close'].rolling(window=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[ema_column_name] = pd_stock_price[ema_column_name].round(2)

    print(pd_stock_price.head(10))

    return pd_stock_price

In [428]:
pd_price = get_ema_index(pd_price, [5, 10, 20, 30])

         Date    Open    High  ...     EMA_10     EMA_20     EMA_30
0  2020-01-06  647000  659000  ...        NaN        NaN        NaN
1  2020-01-07  652000  666000  ...        NaN        NaN        NaN
2  2020-01-08  644000  651000  ...        NaN        NaN        NaN
3  2020-01-09  636000  659000  ...        NaN        NaN        NaN
4  2020-01-10  650000  663000  ...  653800.00  653800.00  653800.00
5  2020-01-13  647000  663000  ...  654500.00  654500.00  654500.00
6  2020-01-14  658000  664000  ...  654857.14  654857.14  654857.14
7  2020-01-15  653000  668000  ...  656250.00  656250.00  656250.00
8  2020-01-16  669000  680000  ...  658888.89  658888.89  658888.89
9  2020-01-17  677000  685000  ...  660100.00  660100.00  660100.00

[10 rows x 18 columns]

In [429]:
def get_mfi_index(pd_stock_price, period_of_list):

    pd_stock_price['TP'] = (pd_stock_price['Close'] + pd_stock_price['High'] + pd_stock_price['Low']) / 3
    pd_stock_price['TP'] = pd_stock_price['TP'].round(2)

    pd_stock_price['PMF'] = 0
    pd_stock_price['NMF'] = 0

    # Loop through the typical price
    for i in range(0, (pd_stock_price.shape[0] - 1)):
        # 당일의 중심가격이 전일의 중심가격보다 크면 긍정적 현금흐름
        if pd_stock_price['TP'].values[i] < pd_stock_price['TP'].values[i + 1]:
            pd_stock_price['PMF'].values[i + 1] = pd_stock_price['TP'].values[i + 1] * pd_stock_price['Volume'].values[i + 1]
            pd_stock_price['NMF'].values[i + 1] = 0
        # 당일의 중심가격이 전일의 중심가격보다 작거나 같으면 부정적 현금흐름
        else:
            pd_stock_price['NMF'].values[i + 1] = pd_stock_price['TP'].values[i + 1] * pd_stock_price['Volume'].values[i + 1]
            pd_stock_price['PMF'].values[i + 1] = 0

    for period in period_of_list:
        pd_stock_price['MFR'] = pd_stock_price['PMF'].rolling(window=period, min_periods=period_of_list[0]).sum() / pd_stock_price['NMF'].rolling(
            window=period, min_periods=period_of_list[0]).sum()
        mfi_columns_name = str('MFI_') + str(period)
        pd_stock_price[mfi_columns_name] = 100 - 100 / (1 + pd_stock_price['MFR'])
        pd_stock_price[mfi_columns_name] = pd_stock_price[mfi_columns_name].round(2)

    # return pd_mfi_index
    return pd_stock_price

In [430]:
pd_price = get_mfi_index(pd_price, [5, 10, 20, 30])

In [431]:
def get_obv_index(pd_stock_price, period_of_list):

    pd_stock_price['OBV'] = 0

    # Loop through the typical price
    for i in range(1, pd_stock_price.shape[0]):
        # 다음날 가격이 상승한 경우
        if pd_stock_price.Close[i] > pd_stock_price.Close[i - 1]:
            # 현재 obv 값 = 이전 obv + 현재 Volumne 값
            pd_stock_price['OBV'].values[i] = (pd_stock_price['OBV'].values[-1] + pd_stock_price['Volume'].values[i])
        # 다음날 가격이 하락한 경우
        elif pd_stock_price.Close[i] < pd_stock_price.Close[i - 1]:
            # 현재 obv 값 = 이전 obv - 현재 Volumne 값
            pd_stock_price['OBV'].values[i] = (pd_stock_price['OBV'].values[-1] - pd_stock_price['Volume'].values[i])
        else:
            pd_stock_price['OBV'].values[i] = pd_stock_price['OBV'].values[-1]

    for period in period_of_list:
        obv_columns_name = str('OBV_') + str(period)
        pd_stock_price[obv_columns_name] = pd_stock_price['OBV'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[obv_columns_name] = pd_stock_price[obv_columns_name].round(2)

    return pd_stock_price

In [432]:
pd_price = get_obv_index(pd_price, [5, 10, 20, 30])

In [433]:
def get_pvt_index(pd_stock_price, period_of_list):

    pd_stock_price['PVT'] = 0

    # Loop through the typical price
    for i in range(1, pd_stock_price.shape[0]):
        pvt_value = pd_stock_price['Close'].values[i] - pd_stock_price['Close'].values[i - 1]
        pvt_value = (pvt_value / pd_stock_price['Close'].values[i - 1]) * pd_stock_price['Volume'].values[i]
        pd_stock_price['PVT'].values[i] = pvt_value + pd_stock_price['PVT'].values[-1]

    for period in period_of_list:
        pvt_columns_name = str('PVT_') + str(period)
        pd_stock_price[pvt_columns_name] = pd_stock_price['PVT'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[pvt_columns_name] = pd_stock_price[pvt_columns_name].round(2)

    return pd_stock_price

In [434]:
pd_price = get_pvt_index(pd_price, [5, 10, 20, 30])

In [435]:
def get_macd_index(pd_stock_price, m_NumFast=12, m_NumSlow=26, m_NumSignal=9):

    pd_stock_price['EMAFast'] = pd_stock_price['Close'].ewm(span=m_NumFast, min_periods=m_NumFast - 1).mean()
    pd_stock_price['EMASlow'] = pd_stock_price['Close'].ewm(span=m_NumSlow, min_periods=m_NumSlow - 1).mean()
    pd_stock_price['MACD'] = pd_stock_price['EMAFast'] - pd_stock_price['EMASlow']

    return pd_stock_price

In [436]:
pd_price = get_macd_index(pd_price, 12, 26, 9)

In [437]:
def get_bollinger_bands(pd_stock_price, period_of_list):

    for period in period_of_list:
        bl_ma_columns_name = str('BL_MA_') + str(period)
        pd_stock_price[bl_ma_columns_name] = pd_stock_price['Close'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[bl_ma_columns_name] = pd_stock_price[bl_ma_columns_name].round(2)

        bl_std_columns_name = str('BL_STD_') + str(period)
        pd_stock_price[bl_std_columns_name] = pd_stock_price['Close'].ewm(com=period, min_periods=period_of_list[0]).std()
        pd_stock_price[bl_std_columns_name] = pd_stock_price[bl_std_columns_name].round(2)

        bl_up_columns_name = str('BL_UP_') + str(period)
        pd_stock_price[bl_up_columns_name] = pd_stock_price[bl_ma_columns_name] + (2 * pd_stock_price[bl_std_columns_name])

        bl_lower_columns_name = str('BL_LO_') + str(period)
        pd_stock_price[bl_lower_columns_name] = pd_stock_price[bl_ma_columns_name] - (
                    2 * pd_stock_price[bl_std_columns_name])

    return pd_stock_price

In [438]:
pd_price = get_bollinger_bands(pd_price, [5, 10, 20, 30])

In [439]:
def get_stochastic_oscillator(pd_stock_price, period_of_list):

    for period in period_of_list:
        st_max_columns_name = str('ST_MAX_') + str(period)
        pd_stock_price[st_max_columns_name] = pd_stock_price['High'].rolling(period, min_periods=period_of_list[0]).max()

        st_min_columns_name = str('ST_MIN_') + str(period)
        pd_stock_price[st_min_columns_name] = pd_stock_price['Low'].rolling(period, min_periods=period_of_list[0]).min()

        st_k_columns_name = str('ST_K_') + str(period)
        pd_stock_price[st_k_columns_name] = (pd_stock_price['Close'] - pd_stock_price[st_min_columns_name]) * 100
        pd_stock_price[st_k_columns_name] = pd_stock_price[st_k_columns_name] / (
                    pd_stock_price[st_max_columns_name] - pd_stock_price[st_min_columns_name])

        st_d_columns_name = str('ST_D_') + str(period)
        pd_stock_price[st_d_columns_name] = pd_stock_price[st_k_columns_name].rolling(3).mean()

    return pd_stock_price

In [440]:
pd_price = get_stochastic_oscillator(pd_price, [5, 10, 20, 30])

In [441]:
def get_rate_of_price_change(pd_stock_price, period_of_list):

    for period in period_of_list:
        price_diff_columns_name = str('R_Price_diff_') + str(period)
        pd_stock_price[price_diff_columns_name] = pd_stock_price['Close'].diff(period - 1)

        price_shift_columns_name = str('R_Price_shift_') + str(period)
        pd_stock_price[price_shift_columns_name] = pd_stock_price['Close'].shift(period - 1)

        price_roc_columns_name = str('R_Price_ROPC_') + str(period)
        pd_stock_price[price_roc_columns_name] = pd_stock_price[price_diff_columns_name] / pd_stock_price[price_shift_columns_name]

    return pd_stock_price

In [442]:
pd_price = get_rate_of_price_change(pd_price, [5, 10, 20, 30])

In [443]:
def get_rate_of_volume_change(pd_stock_price, period_of_list):

    for period in period_of_list:
        price_diff_columns_name = str('R_Volume_diff_') + str(period)
        pd_stock_price[price_diff_columns_name] = pd_stock_price['Volume'].diff(period - 1)

        price_shift_columns_name = str('R_Volume_shift_') + str(period)
        pd_stock_price[price_shift_columns_name] = pd_stock_price['Volume'].shift(period - 1)

        price_roc_columns_name = str('R_Volume_ROPC_') + str(period)
        pd_stock_price[price_roc_columns_name] = pd_stock_price[price_diff_columns_name] / pd_stock_price[price_shift_columns_name]

    return pd_stock_price

In [444]:
pd_price = get_rate_of_price_change(pd_price, [5, 10, 20, 30])

In [445]:
def get_cci_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        period_sma_columns_name = str('CCI_TP_SMA_') + str(period)
        pd_stock_price[period_sma_columns_name] = pd_stock_price['TP'].rolling(period, min_periods=period_of_list[0]).mean()

        period_mad_columns_name = str('CCI_TP_MAD_') + str(period)
        pd_stock_price[period_mad_columns_name] = pd_stock_price['TP'].rolling(period, min_periods=period_of_list[0]).apply(lambda x: pd.Series(x).mad())

        period_cci_columns_name = str('CCI_') + str(period)
        pd_stock_price[period_cci_columns_name] = (pd_stock_price['TP'] - pd_stock_price[period_sma_columns_name])
        pd_stock_price[period_cci_columns_name] = pd_stock_price[period_cci_columns_name] / (0.015 * pd_stock_price[period_mad_columns_name])

    return pd_stock_price

In [446]:
pd_price = get_rate_of_price_change(pd_price, [5, 10, 20, 30])

In [447]:
def get_adx_index(pd_stock_price, period_of_list):

    pd_stock_price['HL'] = pd_stock_price['High'] - pd_stock_price['Low']
    pd_stock_price['absHC'] = abs(pd_stock_price['High'] - pd_stock_price['Close'].shift(1))
    pd_stock_price['absLC'] = abs(pd_stock_price['Low'] - pd_stock_price['Close'].shift(1))
    pd_stock_price['TR'] = pd_stock_price[['HL', 'absHC', 'absLC']].max(axis=1)

    pd_stock_price['UpMove'] = pd_stock_price['High'] - pd_stock_price['High'].shift(1)
    pd_stock_price['DonwMove'] = pd_stock_price['Low'].shift(1) - pd_stock_price['Low']
    pd_stock_price['Zero'] = 0

    pd_stock_price['PlusDM'] = np.where((pd_stock_price['UpMove'] > pd_stock_price['DonwMove']) &
                                          (pd_stock_price['UpMove'] > pd_stock_price['Zero']),
                                          pd_stock_price['UpMove'], 0)
    pd_stock_price['MinusDM'] = np.where((pd_stock_price['UpMove'] < pd_stock_price['DonwMove']) &
                                           (pd_stock_price['DonwMove'] > pd_stock_price['Zero']),
                                           pd_stock_price['DonwMove'], 0)

    for period in period_of_list:

        atr_column_name = str('ATR_') + str(period)
        pd_stock_price[atr_column_name] = pd_stock_price['TR'].rolling(window=period, min_periods=period_of_list[0]).mean()

        natr_column_name = str('NATR_') + str(period)
        pd_stock_price[natr_column_name] = (pd_stock_price[atr_column_name] / pd_stock_price['Close']) * 100

        plus_di_column_name = str('plusDI_') + str(period)
        pd_plus_di_values = (pd_stock_price['PlusDM'] / pd_stock_price[atr_column_name])
        pd_stock_price[plus_di_column_name] = 100 * pd_plus_di_values.ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

        minus_di_column_name = str('MinusDI_') + str(period)
        pd_minus_di_values = (pd_stock_price['MinusDM'] / pd_stock_price[atr_column_name])
        pd_stock_price[minus_di_column_name] = 100 * pd_minus_di_values.ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

        adx_column_name = str('ADX_') + str(period)
        sub_plus_di_minus_di = (pd_stock_price[plus_di_column_name] - pd_stock_price[minus_di_column_name])
        add_plus_di_minus_di = (pd_stock_price[plus_di_column_name] + pd_stock_price[minus_di_column_name])

        pd_stock_price[adx_column_name] = 100 * (abs(sub_plus_di_minus_di / add_plus_di_minus_di)).ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

    return pd_stock_price

In [448]:
pd_price = get_adx_index(pd_price, [5, 10, 20, 30])

In [449]:
pd_price.head(30)

          Date    Open    High  ...  plusDI_30  MinusDI_30      ADX_30
0   2020-01-06  647000  659000  ...        NaN         NaN         NaN
1   2020-01-07  652000  666000  ...        NaN         NaN         NaN
2   2020-01-08  644000  651000  ...        NaN         NaN         NaN
3   2020-01-09  636000  659000  ...        NaN         NaN         NaN
4   2020-01-10  650000  663000  ...  20.408163    0.000000  100.000000
5   2020-01-13  647000  663000  ...   9.863946    0.000000  100.000000
6   2020-01-14  658000  664000  ...   8.241199    0.000000  100.000000
7   2020-01-15  653000  668000  ...  11.968520    0.000000  100.000000
8   2020-01-16  669000  680000  ...  24.048172    0.000000  100.000000
9   2020-01-17  677000  685000  ...  24.777811    0.000000  100.000000
10  2020-01-20  671000  683000  ...  20.492327    4.828735   93.403427
11  2020-01-21  668000  673000  ...  17.294788   11.141057   82.205872
12  2020-01-22  660000  676000  ...  17.235938    9.548410   74.557277
13  2020-01-23  658000  664000  ...  14.951217   13.478896   65.360759
14  2020-01-28  649000  651000  ...  13.095604   29.886962   62.097224
15  2020-01-29  628000  632000  ...  11.561705   26.386279   59.399501
16  2020-01-30  626000  631000  ...  10.275165   29.106342   58.110681
17  2020-01-31  631000  637000  ...  12.748378   26.012186   55.570962
18  2020-02-03  624000  624000  ...  11.447520   26.234403   53.904668
19  2020-02-04  612000  620000  ...  10.321652   27.554822   53.077903
20  2020-02-05  614000  618000  ...   9.339735   24.933485   52.356847
21  2020-02-06  613000  637000  ...  18.295382   22.631982   48.502068
22  2020-02-07  624000  630000  ...  16.652275   20.599405   45.097712
23  2020-02-10  617000  624000  ...  15.193630   22.847571   42.909818
24  2020-02-11  627000  630000  ...  16.893421   20.891398   40.141868
25  2020-02-12  615000  625000  ...  15.476924   20.135143   37.872794
26  2020-02-13  621000  642000  ...  22.411802   18.478852   35.548609
27  2020-02-14  628000  640000  ...  20.600375   16.985305   33.452793
28  2020-02-17  634000  647000  ...  22.216938   15.634502   32.175371
29  2020-02-18  636000  661000  ...  26.792452   14.409515   32.009177

[30 rows x 112 columns]

In [450]:
pd_pivot_data = pd.pivot_table(data=pd_price, columns='weekday', index='weeknum')

In [451]:
pd_pivot_data = pd_pivot_data.ffill()
pd_pivot_data = pd_pivot_data.ffill(axis=1)

In [452]:
pd_pivot_data.shape

(99, 545)

In [453]:
pd_pivot_data = pd_pivot_data.dropna()

In [454]:
pd_pivot_data.shape

(98, 545)

In [455]:
pd_pivot_data.head(10)

             ADX_10                          ... week_diff
weekday           0           1           2  ...         2        3        4
weeknum                                      ...
3        100.000000  100.000000  100.000000  ...    3000.0 -29000.0 -38000.0
4         88.355470   68.768771   57.103165  ...  -43000.0 -39000.0 -38000.0
5         88.355470   51.547226   53.803154  ...  -18000.0   2000.0  -4000.0
6         54.518164   55.865688   56.949631  ...   16000.0   5000.0  12000.0
7         35.722817   29.900388   24.955963  ...   28000.0  21000.0   8000.0
8         33.558153   39.604227   44.989594  ...  -48000.0 -47000.0 -48000.0
9         41.214994   39.880635   39.289218  ...  -35000.0 -24000.0 -30000.0
10        48.444468   53.147188   56.229402  ...  -48000.0 -78000.0 -66000.0
11        52.697568   53.012868   57.013656  ...  -71500.0 -97000.0 -60500.0
12        67.162871   67.220053   68.369363  ...   -3000.0  42000.0  25000.0

[10 rows x 545 columns]

In [456]:
pd_pivot_data['MACD'].head(10)

weekday              0              1  ...              3              4
weeknum                                ...
3        671000.000000  671000.000000  ...  671000.000000  671000.000000
4        671000.000000  671000.000000  ...  671000.000000  671000.000000
5        616000.000000  616000.000000  ...  616000.000000  616000.000000
6        620000.000000  620000.000000  ...  620000.000000  620000.000000
7        625000.000000   -8110.513198  ...   -6577.694929   -5466.611523
8         -3743.182713   -1555.392097  ...     927.205761    1069.475885
9         -1139.951838   -2929.535793  ...   -6114.066220   -7872.019089
10       -10603.770110  -13078.563028  ...  -15248.948169  -16607.459548
11       -18408.242664  -19994.845011  ...  -26615.681076  -29433.624248
12       -30445.256957  -32922.576827  ...  -43455.482178  -45377.422542

[10 rows x 5 columns]